# Packages and libraries require MPI

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - py-mpi4py@3.0.0
      - hdf5+mpi@1.10.3
      - highfive+mpi@1.6
      #- matio@1.5.9
      #- netcdf@4.6.1
      ##- neuron@2018-10
      #- parmetis@4.0.3

  # gnu-stable-parallel-lapack:
  #   target_matrix:
  #     - gnu-stable
  #   requires:
  #     - architecture
  #     - compiler
  #     - mpi
  #     - lapack
  #   specs:
  #     - hypre@2.14.0
  #     - omega-h@9.22.2
  #     - superlu-dist@5.4.0
  #     - trilinos@xsdk-0.4.0-rc1

  # gnu-stable-parallel-lapack-python:
  #   target_matrix:
  #     - gnu-stable
  #   requires:
  #     - architecture
  #     - compiler
  #     - lapack
  #     - mpi
  #     - python
  #   specs:
  #     - petsc+int64+mpi@3.10.1

  #intel-stable-parallel:
  #  target_matrix:
  #    - intel-stable
  #  requires:
  #    - architecture
  #    - compiler
  #    - mpi
  #  specs:
  #    - neuron@2018-10
