modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    hash_length: 0
    whitelist:
      - hdf5+mpi
      - highfive+mpi
      - petsc
      - py-mpi4py
      - trilinos
    blacklist:
      - '%gcc'
      - '%intel'
      - '%llvm'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
